# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SaveecobotLoader
                                 A QGIS plugin
 This plugins loads AQI data from Safeecobot
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-03-30
        copyright            : (C) 2022 by Bundesamt für Strahlenschutz
        email                : mlechner@bfs.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SaveecobotLoader class from file SaveecobotLoader.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .saveecobot_loader import SaveecobotLoader
    return SaveecobotLoader(iface)
